
on: workflow_dispatch


jobs:

  build:


    runs-on: windows-latest

    timeout-minutes: 9999


    steps:

    - name: Download Ngrok.

      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        
        Invoke-WebRequest https://raw.githubusercontent.com/DINASH001/DOW/main/windows/windows-rdp-main/start.bat -OutFile start.bat
        
        
        Invoke-WebRequest https://raw.githubusercontent.com/DINASH001/DOW/main/windows/windows-rdp-main/loop.bat -OutFile loop.bat
    - name: Download Launcher.

      run: |
        
        Invoke-WebRequest https://github.com/DINASH001/DOW/raw/main/Download.zip -OutFile Download.zip
        
        
        
        
        
        
    - name: Extract Ngrok File.

      run: |
         Expand-Archive ngrok.zip
         Expand-Archive Download.zip
         
         
         
    - name: Connect Ngrok.

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Action Access RDP.

      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        
        
       
        
   
        
        
        
        
    - name: Making tunnels

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Connect RDP CPU 2 Core - 7GB Ram - 256 SSD.

      run: cmd /c start.bat

    - name: Successful implementation! You can close the tab now.

      run: cmd /c loop.bat
